server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/emartdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
  jpa:
    show-sql: true 
  


